name: Aureyo Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PAYMENT_API_URL: 'https://payment-3jq2rv5sxa-lm.a.run.app'
  RAPORTING_API_URL: 'https://raporting-319936913236.europe-central2.run.app'
  BUCKET: 'aureyo'
  ENVIRONMENT: true

jobs:

  build:
    # needs: E2E
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - uses: actions/checkout@v2

      - uses: microsoft/variable-substitution@v1
        with:
          files: 'Aureyo.Frontend/src/config.json'
        env:
          apps.PaymentAPI.url: ${{ env.PAYMENT_API_URL }}
          apps.RaportingAPI.url: ${{ env.RAPORTING_API_URL }}

      - name: Read config.json from VoiceSense.Front
        run: 'cat AuthenticScope.Frontend/src/config.json'

      - name: Build and deploy frontend to static GCP Cloud Storage
        run: |
          cd ./Aureyo.Frontend/
          npm install --force
          CI=false npm run build
          gsutil web set -m index.html -e index.html gs://${{ env.BUCKET }}
          gsutil iam ch allUsers:legacyObjectReader gs://${{ env.BUCKET }}
          gsutil -h "Cache-Control:public, max-age=0, no-transform" rsync -d -r ./build gs://${{env.BUCKET}}
        # gcloud compute url-maps invalidate-cdn-cache planfi-lb --path '/${{env.Domain}}/*'